version: "3.8"
services:
    mvc-web-api:
        build: .
        container_name: web-api-container
        ports:
            - "8080:8080"
        depends_on:
            - sql-server
    sql-server:
        container_name: sql-server-container
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=H%sloH%slo4213
        ports:
            - "1433:1433"